title: Văn khấn Việt
description: Tổng hợp các bài văn khấn truyền thống trong đời sống người Việt

github:
  is_project_page: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
